import { Dish, Song, SocialPost } from './types';

export const DISHES: Dish[] = [
  {
    id: '1',
    name: 'Paneer Butter Masala',
    description: 'Creamy tomato-based curry with soft paneer cubes and aromatic spices.',
    price: 320,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800',
    category: 'Main Course',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 2,
    prepTime: 20,
    isTrending: true,
    moods: ['happy', 'comfort'],
    portionSize: 'Serves 2',
    tasteTags: ['Creamy', 'Mildly Spiced'],
    popularityBadge: 'Best Seller',
  },
  {
    id: '2',
    name: 'Chicken Tikka Masala',
    description: 'Roasted marinated chicken chunks in a spiced sauce.',
    price: 450,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
    category: 'Main Course',
    isVeg: false,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 3,
    prepTime: 25,
    isTrending: true,
    moods: ['party', 'spicy'],
    portionSize: 'Serves 1-2',
    tasteTags: ['Smoky', 'Spicy'],
    popularityBadge: 'Must Try',
  },
  {
    id: '3',
    name: 'Veg Hakka Noodles',
    description: 'Stir-fried noodles with crunchy vegetables and oriental sauces.',
    price: 240,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800',
    category: 'Chinese',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 2,
    prepTime: 15,
    moods: ['happy', 'party'],
    portionSize: 'Serves 2',
    tasteTags: ['Savory', 'Garlicky'],
  },
  {
    id: '4',
    name: 'Crispy Corn',
    description: 'Golden fried sweet corn kernels tossed with spices and spring onions.',
    price: 180,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1514516348920-f5d928844f9d?auto=format&fit=crop&q=80&w=800',
    category: 'Starters',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 3,
    prepTime: 10,
    isTrending: true,
    moods: ['party', 'spicy', 'hangover'],
    portionSize: 'Serves 2-3',
    tasteTags: ['Crunchy', 'Tangy'],
    popularityBadge: 'Crowd Favorite',
  },
  {
    id: '5',
    name: 'Double Cheese Margherita',
    description: 'Classic pizza with extra mozzarella and fresh basil.',
    price: 380,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad50?auto=format&fit=crop&q=80&w=800',
    category: 'Pizza',
    isVeg: true,
    isJain: false,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 1,
    prepTime: 20,
    moods: ['romantic', 'comfort'],
    portionSize: '10 inch',
    tasteTags: ['Cheesy', 'Herby'],
  },
  {
    id: '6',
    name: 'Dal Makhani',
    description: 'Slow-cooked black lentils with butter and cream.',
    price: 280,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800',
    category: 'Main Course',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 1,
    prepTime: 30,
    moods: ['comfort', 'healthy'],
    portionSize: 'Serves 2',
    tasteTags: ['Rich', 'Buttery'],
    popularityBadge: 'Chef Special',
  },
  {
    id: '7',
    name: 'Tandoori Soya Chaap',
    description: 'Soy chunks marinated in yogurt and spices, grilled to perfection.',
    price: 260,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
    category: 'Starters',
    isVeg: true,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 3,
    prepTime: 15,
    moods: ['party', 'spicy'],
    portionSize: '8 Pieces',
    tasteTags: ['Smoky', 'Tender'],
  },
  {
    id: '8',
    name: 'Lemon Coriander Soup',
    description: 'Refreshing clear soup with fresh lemon and coriander leaves.',
    price: 150,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=800',
    category: 'Soups',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 1,
    prepTime: 10,
    moods: ['healthy', 'hangover'],
    portionSize: 'Serves 1',
    tasteTags: ['Zesty', 'Light'],
  },
  {
    id: '9',
    name: 'Butter Garlic Prawns',
    description: 'Juicy prawns sautéed in a rich butter garlic sauce.',
    price: 520,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&q=80&w=800',
    category: 'Seafood',
    isVeg: false,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 2,
    prepTime: 15,
    moods: ['romantic', 'party'],
    portionSize: '10 Pieces',
    tasteTags: ['Garlicky', 'Succulent'],
    popularityBadge: 'Premium Choice',
  },
  {
    id: '10',
    name: 'Quinoa Salad Bowl',
    description: 'Nutritious quinoa with mixed greens, chickpeas, and lemon vinaigrette.',
    price: 340,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800',
    category: 'Healthy',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 1,
    prepTime: 12,
    moods: ['healthy', 'happy'],
    portionSize: 'Large Bowl',
    tasteTags: ['Fresh', 'Nutty'],
  },
  {
    id: '11',
    name: 'Mutton Rogan Josh',
    description: 'Traditional Kashmiri style slow-cooked mutton curry.',
    price: 580,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&q=80&w=800',
    category: 'Main Course',
    isVeg: false,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 3,
    prepTime: 40,
    moods: ['comfort', 'spicy'],
    portionSize: 'Serves 2',
    tasteTags: ['Aromatic', 'Rich'],
    popularityBadge: 'Royal Taste',
  },
  {
    id: '12',
    name: 'Spicy Ramen Noodles',
    description: 'Fiery Japanese style noodles with a spicy broth and veggies.',
    price: 320,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800',
    category: 'Chinese',
    isVeg: true,
    isJain: false,
    isEgg: true,
    isGlutenFree: false,
    spiceLevel: 5,
    prepTime: 15,
    moods: ['spicy', 'hangover'],
    portionSize: 'Serves 1',
    tasteTags: ['Fiery', 'Umami'],
  },
  {
    id: '13',
    name: 'Avocado Toast',
    description: 'Sourdough bread topped with mashed avocado, chili flakes, and seeds.',
    price: 280,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800',
    category: 'Healthy',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 1,
    prepTime: 8,
    moods: ['healthy', 'happy'],
    portionSize: '2 Slices',
    tasteTags: ['Creamy', 'Crunchy'],
  },
  {
    id: '14',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a gooey molten center.',
    price: 220,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1624353335566-38b9907d7587?auto=format&fit=crop&q=80&w=800',
    category: 'Desserts',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 0,
    prepTime: 12,
    moods: ['romantic', 'happy'],
    portionSize: 'Serves 1',
    tasteTags: ['Sweet', 'Indulgent'],
    popularityBadge: 'Must Have',
  },
  {
    id: '15',
    name: 'Masala Chai & Pakora',
    description: 'Classic Indian tea served with crispy onion fritters.',
    price: 160,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1544787210-2827443cb39b?auto=format&fit=crop&q=80&w=800',
    category: 'Starters',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 2,
    prepTime: 10,
    moods: ['comfort', 'happy'],
    portionSize: 'Serves 1-2',
    tasteTags: ['Spicy', 'Warm'],
  },
  {
    id: '16',
    name: 'Truffle Mushroom Risotto',
    description: 'Creamy Arborio rice with wild mushrooms and truffle oil.',
    price: 480,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&q=80&w=800',
    category: 'Main Course',
    isVeg: true,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 1,
    prepTime: 25,
    moods: ['romantic', 'comfort'],
    portionSize: 'Serves 1',
    tasteTags: ['Earthy', 'Creamy'],
    popularityBadge: 'Chef Special',
  },
  {
    id: '17',
    name: 'Spicy Chicken Wings',
    description: 'Crispy wings tossed in our signature extra hot buffalo sauce.',
    price: 350,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&q=80&w=800',
    category: 'Starters',
    isVeg: false,
    isJain: false,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 5,
    prepTime: 15,
    moods: ['party', 'hangover', 'spicy'],
    portionSize: '6 Pieces',
    tasteTags: ['Fiery', 'Crispy'],
  },
  {
    id: '18',
    name: 'Greek Salad',
    description: 'Fresh cucumbers, tomatoes, olives, and feta cheese with oregano.',
    price: 290,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=800',
    category: 'Healthy',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: true,
    spiceLevel: 1,
    prepTime: 10,
    moods: ['healthy', 'happy'],
    portionSize: 'Serves 1-2',
    tasteTags: ['Tangy', 'Fresh'],
  },
  {
    id: '19',
    name: 'Blueberry Pancakes',
    description: 'Fluffy pancakes loaded with fresh blueberries and maple syrup.',
    price: 260,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=800',
    category: 'Desserts',
    isVeg: true,
    isJain: true,
    isEgg: false,
    isGlutenFree: false,
    spiceLevel: 0,
    prepTime: 15,
    moods: ['happy', 'comfort'],
    portionSize: '3 Pancakes',
    tasteTags: ['Sweet', 'Fruity'],
  },
  {
    id: '20',
    name: 'Classic Eggs Benedict',
    description: 'Poached eggs on English muffins with hollandaise sauce.',
    price: 320,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?auto=format&fit=crop&q=80&w=800',
    category: 'Healthy',
    isVeg: false,
    isJain: false,
    isEgg: true,
    isGlutenFree: false,
    spiceLevel: 1,
    prepTime: 15,
    moods: ['hangover', 'happy'],
    portionSize: 'Serves 1',
    tasteTags: ['Rich', 'Savory'],
  }
];

export const MOODS = [
  { id: 'happy', emoji: '😊', label: 'Happy' },
  { id: 'romantic', emoji: '❤️', label: 'Romantic' },
  { id: 'hangover', emoji: '🤕', label: 'Hangover' },
  { id: 'comfort', emoji: '🍲', label: 'Comfort' },
  { id: 'spicy', emoji: '🌶️', label: 'Spicy' },
  { id: 'healthy', emoji: '🥗', label: 'Healthy' },
  { id: 'party', emoji: '🎉', label: 'Party' },
];

export const SOCIAL_POSTS: SocialPost[] = [
  { id: '1', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=800', likes: 124, author: 'Table 4' },
  { id: '2', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800', likes: 89, author: 'Table 12' },
  { id: '3', image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=800', likes: 256, author: 'Table 7' },
  { id: '4', image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800', likes: 167, author: 'Table 2' },
];

export const SONGS: Song[] = [
  { id: '1', title: 'Levitating', artist: 'Dua Lipa' },
  { id: '2', title: 'Blinding Lights', artist: 'The Weeknd' },
  { id: '3', title: 'Stay', artist: 'The Kid LAROI & Justin Bieber' },
  { id: '4', title: 'Heat Waves', artist: 'Glass Animals' },
];
